import type { SynergyDefinition, Tag } from '../domain/types';

const synergy = (
  id: Tag,
  name: string,
  thresholds: number[],
  effect: SynergyDefinition['effect'],
  values: number[],
  description: string,
  scope: SynergyDefinition['scope'] = 'selfTag',
): SynergyDefinition => ({ id, name, thresholds, effect, values, description, scope });

export const SYNERGIES: SynergyDefinition[] = [
  synergy('infantry', '步兵', [2, 4, 6], 'hpPercent', [12, 24, 38], '步兵生命提高 12% / 24% / 38%'),
  synergy('cavalry', '骑兵', [2], 'enemyArmor', [4], '敌方护甲降低 4', 'allEnemies'),
  synergy('armor', '装甲', [3, 5], 'armor', [4, 8], '装甲护甲 +4 / +8'),
  synergy('airforce', '空军', [2, 4], 'dodge', [15, 25], '空军闪避 +15% / +25%'),
  synergy(
    'puppet',
    '傀儡',
    [2, 4, 6],
    'attackPercent',
    [10, 20, 35],
    '傀儡攻击 +10% / +20% / +35%',
  ),
  synergy('psionic', '灵能者', [2, 4], 'reflect', [20, 35], '灵能者受伤反弹 20 / 35 点伤害'),
  synergy(
    'walker',
    '陆行者',
    [1],
    'groundBonus',
    [1],
    '仅有一种陆行者时，其普攻造成真实伤害',
    'rule',
  ),
  synergy('marine', '海神', [2, 4], 'skillResist', [20, 35], '海神受到的技能伤害降低 20% / 35%'),
  synergy('beast', '野兽', [2, 4, 6], 'haste', [10, 20, 35], '野兽攻击间隔降低 10% / 20% / 35%'),
  synergy('raptor', '猛禽', [2, 4], 'groundBonus', [20, 40], '空中猛禽对地伤害 +20% / +40%'),
  synergy('insectoid', '异虫', [2, 4], 'merge', [2, 4], '2/4 异虫启用一星/二星二合一', 'rule'),
  synergy('immortal', '不朽者', [2, 3], 'linger', [80, 120], '死亡后继续战斗 4 / 6 秒'),
  synergy('panda', '熊猫', [3], 'fullEnergy', [100], '熊猫开战时获得满能量'),
  synergy('guard', '护卫', [2, 4], 'shield', [100, 220], '护卫开场护盾 100 / 220'),
  synergy(
    'blast',
    '爆破',
    [3, 6],
    'enemySkillResist',
    [15, 30],
    '敌方技能防御降低 15% / 30%',
    'allEnemies',
  ),
  synergy('support', '支援', [2, 4], 'deathHeal', [60, 130], '支援死亡时治疗友军并恢复能量'),
  synergy('sniper', '狙击', [3, 6], 'armorPen', [4, 9], '狙击获得 4 / 9 点护甲穿透'),
  synergy('siege', '攻城', [3, 6], 'siegeBonus', [25, 50], '攻城对重型种族伤害 +25% / +50%'),
  synergy(
    'ability',
    '异能（法术）',
    [2, 4, 6],
    'enemyEnergyGain',
    [10, 20, 35],
    '敌方能量获得降低 10% / 20% / 35%',
    'allEnemies',
  ),
  synergy('assassin', '刺杀', [3, 6], 'critical', [20, 35], '刺杀普攻获得暴击率与开场切后'),
  synergy('summoner', '召唤', [3], 'summonEnergy', [25], '召唤物造成伤害时主人获得能量'),
  synergy('vanguard', '先锋（战士）', [3, 6], 'regen', [3, 7], '先锋每秒回复 3% / 7% 最大生命'),
  synergy(
    'building',
    '建筑',
    [2, 3],
    'cooldown',
    [15, 30],
    '全队技能冷却 -15% / -30%',
    'allAllies',
  ),
  synergy(
    'fighter',
    '格斗家',
    [2, 3],
    'extreme',
    [25, 45],
    '低生命进入极限模式，强化攻速、攻击与回能',
  ),
];
