import type { AbilityEffect, SkillKind, Tag, UnitDefinition } from '../domain/types';
import { RULES } from './rules';

type Shape = UnitDefinition['shape'];
interface UnitRow {
  id: string;
  name: string;
  cost: number;
  tags: Tag[];
  kind: SkillKind;
  skill: string;
  description: string;
  shape: Shape;
  layer?: UnitDefinition['layer'];
  range?: number;
  radius?: number;
  power?: number;
  duration?: number;
  assassin?: boolean;
  deathBurst?: number;
  immobile?: boolean;
  noAttack?: boolean;
  summonId?: string;
}

// The handbook reconstructs mechanisms, but not a complete numeric atlas. Unverified numbers are project tuning values.
const rows: UnitRow[] = [
  {
    id: 'kong',
    name: '金刚',
    cost: 1,
    tags: ['walker', 'guard'],
    kind: 'shield',
    skill: '金刚护体',
    description: '获得护盾并坚守前线。',
    shape: 'soldier',
  },
  {
    id: 'shield',
    name: '护盾兵',
    cost: 1,
    tags: ['infantry', 'guard'],
    kind: 'stun',
    skill: '盾击',
    description: '眩晕当前目标。',
    shape: 'soldier',
  },
  {
    id: 'lion',
    name: '狂狮',
    cost: 3,
    tags: ['beast', 'guard'],
    kind: 'stun',
    skill: '石化怒吼',
    description: '石化周围敌人。',
    shape: 'beast',
    radius: 2,
  },
  {
    id: 'shield_slave',
    name: '盾奴',
    cost: 1,
    tags: ['puppet', 'guard'],
    kind: 'shield',
    skill: '傀儡壁垒',
    description: '获得高额护盾。',
    shape: 'soldier',
  },
  {
    id: 'staff_slave',
    name: '棍奴',
    cost: 4,
    tags: ['puppet', 'guard'],
    kind: 'stun',
    skill: '撼地棍',
    description: '重击并眩晕一片敌人。',
    shape: 'soldier',
    radius: 2,
  },
  {
    id: 'sage',
    name: '天师',
    cost: 2,
    tags: ['psionic', 'blast'],
    kind: 'damage',
    skill: '雷暴',
    description: '召下短冷却范围雷暴。',
    shape: 'mystic',
    radius: 2,
  },
  {
    id: 'dog',
    name: '铁狗',
    cost: 1,
    tags: ['armor', 'blast'],
    kind: 'damage',
    skill: '火炮齐射',
    description: '发射装甲爆破弹。',
    shape: 'mech',
  },
  {
    id: 'burstbug',
    name: '爆裂虫',
    cost: 1,
    tags: ['insectoid', 'blast'],
    kind: 'damage',
    skill: '爆裂遗产',
    description: '死亡后延时自爆。',
    shape: 'insect',
    deathBurst: 130,
  },
  {
    id: 'ape',
    name: '铁猿',
    cost: 3,
    tags: ['armor', 'blast'],
    kind: 'damage',
    skill: '震荡拳',
    description: '对近身敌人造成范围伤害。',
    shape: 'mech',
    range: 1,
    radius: 2,
  },
  {
    id: 'motor',
    name: '摩托骑兵',
    cost: 3,
    tags: ['cavalry', 'blast'],
    kind: 'poison',
    skill: '焦油弹',
    description: '焦油范围持续伤害并减缓敌人。',
    shape: 'soldier',
    radius: 2,
  },
  {
    id: 'bomber',
    name: '轰炸机',
    cost: 3,
    tags: ['airforce', 'blast'],
    kind: 'damage',
    skill: '空袭',
    description: '从空中轰炸目标区域。',
    shape: 'mech',
    layer: 'air',
    radius: 2,
  },
  {
    id: 'titan',
    name: '铁巨神',
    cost: 5,
    tags: ['armor', 'blast'],
    kind: 'damage',
    skill: '核子重炮',
    description: '长前摇后轰击大范围区域。',
    shape: 'mech',
    radius: 3,
    power: 360,
  },
  {
    id: 'child',
    name: '童子',
    cost: 1,
    tags: ['psionic', 'support'],
    kind: 'buff',
    skill: '灵能灌注',
    description: '为全队恢复能量。',
    shape: 'mystic',
  },
  {
    id: 'medic',
    name: '军医',
    cost: 2,
    tags: ['infantry', 'support'],
    kind: 'heal',
    skill: '战地治疗',
    description: '治疗生命比例最低的友军。',
    shape: 'soldier',
  },
  {
    id: 'repair',
    name: '维修机',
    cost: 2,
    tags: ['airforce', 'support'],
    kind: 'shield',
    skill: '维修光束',
    description: '保护并修复生命最低的友军。',
    shape: 'mech',
    layer: 'air',
  },
  {
    id: 'deer',
    name: '长生鹿',
    cost: 1,
    tags: ['beast', 'support'],
    kind: 'heal',
    skill: '长生花',
    description: '为受伤友军提供回复。',
    shape: 'beast',
  },
  {
    id: 'gunner',
    name: '神枪手',
    cost: 1,
    tags: ['infantry', 'sniper'],
    kind: 'buff',
    skill: '超频射击',
    description: '短时间提高自身火力。',
    shape: 'soldier',
    range: 5,
  },
  {
    id: 'bird_rider',
    name: '鸟骑兵',
    cost: 1,
    tags: ['cavalry', 'sniper'],
    kind: 'damage',
    skill: '俯冲射击',
    description: '远程射击当前目标。',
    shape: 'soldier',
    range: 5,
  },
  {
    id: 'thunder',
    name: '雷震子',
    cost: 3,
    tags: ['psionic', 'sniper'],
    kind: 'damage',
    skill: '连环雷',
    description: '造成范围雷电伤害。',
    shape: 'mystic',
    range: 5,
    radius: 2,
  },
  {
    id: 'arhat',
    name: '罗汉',
    cost: 3,
    tags: ['walker', 'sniper'],
    kind: 'damage',
    skill: '破妄一击',
    description: '对单体造成高额伤害。',
    shape: 'soldier',
    range: 5,
    power: 230,
  },
  {
    id: 'commando',
    name: '特种兵',
    cost: 4,
    tags: ['infantry', 'sniper'],
    kind: 'damage',
    skill: '超距狙杀',
    description: '从七格射程狙击目标。',
    shape: 'soldier',
    range: 7,
    power: 280,
  },
  {
    id: 'bat',
    name: '蝙蝠',
    cost: 2,
    tags: ['raptor', 'sniper'],
    kind: 'damage',
    skill: '声波冲击',
    description: '释放技能强化的远程冲击。',
    shape: 'beast',
    layer: 'air',
    range: 5,
  },
  {
    id: 'killerbee',
    name: '杀人蜂',
    cost: 2,
    tags: ['insectoid', 'sniper'],
    kind: 'buff',
    skill: '多段蜂针',
    description: '强化连续普攻。',
    shape: 'insect',
    layer: 'air',
    range: 5,
  },
  {
    id: 'aircrab',
    name: '空蟹',
    cost: 1,
    tags: ['marine', 'siege'],
    kind: 'damage',
    skill: '威胁炮击',
    description: '炮击攻击力最高的敌人。',
    shape: 'beast',
    range: 5,
    power: 180,
  },
  {
    id: 'tank',
    name: '投石车',
    cost: 3,
    tags: ['armor', 'siege'],
    kind: 'buff',
    skill: '架炮',
    description: '架起后提高攻击与射程。',
    shape: 'mech',
    range: 5,
  },
  {
    id: 'dragon',
    name: '翔龙',
    cost: 4,
    tags: ['walker', 'siege'],
    kind: 'stun',
    skill: '翔龙震荡',
    description: '范围伤害并控制敌人。',
    shape: 'beast',
    radius: 2,
  },
  {
    id: 'ark',
    name: '方舟',
    cost: 4,
    tags: ['airforce', 'siege'],
    kind: 'summon',
    skill: '无人机群',
    description: '释放持续作战的小飞机。',
    shape: 'mech',
    layer: 'air',
    summonId: 'bomber',
  },
  {
    id: 'bone_dragon',
    name: '骨龙',
    cost: 5,
    tags: ['raptor', 'immortal', 'siege'],
    kind: 'stun',
    skill: '亡骨风暴',
    description: '大范围伤害并眩晕。',
    shape: 'beast',
    layer: 'air',
    radius: 3,
  },
  {
    id: 'whale',
    name: '幻鲸',
    cost: 5,
    tags: ['marine', 'siege'],
    kind: 'stun',
    skill: '幻海潮汐',
    description: '大范围潮汐伤害与控制。',
    shape: 'beast',
    layer: 'air',
    radius: 3,
  },
  {
    id: 'eye',
    name: '眼虫',
    cost: 1,
    tags: ['insectoid', 'ability'],
    kind: 'stun',
    skill: '凝视',
    description: '压制并眩晕关键目标。',
    shape: 'insect',
  },
  {
    id: 'spider',
    name: '蜘蛛',
    cost: 3,
    tags: ['insectoid', 'ability'],
    kind: 'charm',
    skill: '魅惑蛛网',
    description: '强制敌人转火其同伴。',
    shape: 'insect',
    radius: 2,
  },
  {
    id: 'vine',
    name: '藤妖',
    cost: 3,
    tags: ['immortal', 'ability'],
    kind: 'stun',
    skill: '缠绕',
    description: '缠绕范围敌人。',
    shape: 'mystic',
    radius: 2,
  },
  {
    id: 'eel',
    name: '电蛟',
    cost: 4,
    tags: ['marine', 'ability'],
    kind: 'damage',
    skill: '电海',
    description: '爆发性范围技能伤害。',
    shape: 'beast',
    radius: 2,
    power: 270,
  },
  {
    id: 'grenadier',
    name: '投弹手',
    cost: 2,
    tags: ['infantry', 'ability'],
    kind: 'damage',
    skill: '灵能手雷',
    description: '投掷范围伤害手雷。',
    shape: 'soldier',
    radius: 2,
  },
  {
    id: 'zen_panda',
    name: '禅师熊猫',
    cost: 4,
    tags: ['panda', 'ability'],
    kind: 'damage',
    skill: '禅意爆发',
    description: '释放大范围能量冲击。',
    shape: 'panda',
    radius: 3,
  },
  {
    id: 'toad',
    name: '飞天蛤蟆',
    cost: 5,
    tags: ['raptor', 'ability'],
    kind: 'execute',
    skill: '吞噬',
    description: '斩杀生命低于技能阈值的目标。',
    shape: 'beast',
    layer: 'air',
    power: 32,
  },
  {
    id: 'axe_slave',
    name: '斧奴',
    cost: 1,
    tags: ['puppet', 'assassin'],
    kind: 'damage',
    skill: '旋斧',
    description: '短冷却近战斩击。',
    shape: 'soldier',
    range: 1,
    assassin: true,
  },
  {
    id: 'pangolin',
    name: '穿山甲',
    cost: 2,
    tags: ['beast', 'assassin'],
    kind: 'dash',
    skill: '穿山突袭',
    description: '突进后排并造成伤害。',
    shape: 'beast',
    range: 1,
    assassin: true,
  },
  {
    id: 'osprey',
    name: '灵鹫',
    cost: 3,
    tags: ['marine', 'assassin'],
    kind: 'dash',
    skill: '灵空扑杀',
    description: '飞跃切入敌方后排。',
    shape: 'beast',
    layer: 'air',
    range: 1,
    assassin: true,
  },
  {
    id: 'ghost',
    name: '幽灵机',
    cost: 5,
    tags: ['airforce', 'assassin'],
    kind: 'dash',
    skill: '幽灵突袭',
    description: '高速切后并造成范围伤害。',
    shape: 'mech',
    layer: 'air',
    range: 1,
    radius: 2,
    assassin: true,
  },
  {
    id: 'ninja_panda',
    name: '忍者熊猫',
    cost: 4,
    tags: ['panda', 'assassin'],
    kind: 'damage',
    skill: '影分身斩',
    description: '开局充能后快速范围切杀。',
    shape: 'panda',
    range: 1,
    radius: 2,
    assassin: true,
  },
  {
    id: 'iron_chicken',
    name: '铁鸡',
    cost: 4,
    tags: ['armor', 'assassin'],
    kind: 'dash',
    skill: '钢羽突刺',
    description: '装甲突进斩击。',
    shape: 'mech',
    range: 1,
    assassin: true,
  },
  {
    id: 'master',
    name: '真人',
    cost: 4,
    tags: ['psionic', 'puppet', 'summoner'],
    kind: 'summon',
    skill: '刀奴幻象',
    description: '召唤刀奴幻象。',
    shape: 'mystic',
    summonId: 'blade_slave',
  },
  {
    id: 'wolf',
    name: '鬼狼',
    cost: 2,
    tags: ['beast', 'summoner'],
    kind: 'summon',
    skill: '狼群裂隙',
    description: '召唤鬼狼协同作战。',
    shape: 'beast',
    summonId: 'wolf',
  },
  {
    id: 'shark',
    name: '须弥鲨',
    cost: 4,
    tags: ['marine', 'puppet', 'summoner'],
    kind: 'summon',
    skill: '须弥化身',
    description: '召唤海神傀儡。',
    shape: 'beast',
    summonId: 'shield_slave',
  },
  {
    id: 'monk_panda',
    name: '武僧熊猫',
    cost: 1,
    tags: ['panda', 'vanguard'],
    kind: 'shield',
    skill: '武僧架势',
    description: '获得护盾并持续作战。',
    shape: 'panda',
    range: 1,
  },
  {
    id: 'mammoth',
    name: '巨齿象',
    cost: 2,
    tags: ['beast', 'vanguard'],
    kind: 'dash',
    skill: '巨象冲锋',
    description: '沿路径冲锋并眩晕。',
    shape: 'beast',
    range: 1,
  },
  {
    id: 'sword_slave',
    name: '剑奴',
    cost: 2,
    tags: ['puppet', 'vanguard'],
    kind: 'buff',
    skill: '剑势',
    description: '短时间强化自身攻击。',
    shape: 'soldier',
    range: 1,
  },
  {
    id: 'flame',
    name: '火焰兵',
    cost: 2,
    tags: ['infantry', 'vanguard'],
    kind: 'poison',
    skill: '火焰喷射',
    description: '持续灼烧前方敌人。',
    shape: 'soldier',
    range: 2,
    radius: 2,
  },
  {
    id: 'venom',
    name: '猛毒兽',
    cost: 4,
    tags: ['beast', 'vanguard'],
    kind: 'armorBreak',
    skill: '腐蚀吐息',
    description: '范围伤害并降低敌人护甲。',
    shape: 'beast',
    range: 1,
    radius: 2,
  },
  {
    id: 'blade_slave',
    name: '刀奴',
    cost: 3,
    tags: ['puppet', 'vanguard'],
    kind: 'buff',
    skill: '狂刃',
    description: '强化近战连续攻击。',
    shape: 'soldier',
    range: 1,
  },
  {
    id: 'blood_eagle',
    name: '血鹰',
    cost: 4,
    tags: ['beast', 'raptor', 'vanguard'],
    kind: 'transform',
    skill: '血鹰变身',
    description: '切换形态并强化多段攻击。',
    shape: 'beast',
    layer: 'air',
    range: 1,
  },
  {
    id: 'tree',
    name: '树妖',
    cost: 5,
    tags: ['immortal', 'vanguard'],
    kind: 'stun',
    skill: '古树禁锢',
    description: '大范围控制敌人。',
    shape: 'mystic',
    range: 1,
    radius: 3,
  },
  {
    id: 'alchemy_tower',
    name: '炼金塔',
    cost: 3,
    tags: ['building', 'support'],
    kind: 'buff',
    skill: '炼金协议',
    description: '无法攻击；胜利且存活时按星级提供金币。',
    shape: 'building',
    immobile: true,
    noAttack: true,
  },
  {
    id: 'divine_tower',
    name: '神威塔',
    cost: 4,
    tags: ['building', 'sniper'],
    kind: 'silence',
    skill: '神威封锁',
    description: '锁定攻击最高敌人并使其装备失效。',
    shape: 'building',
    immobile: true,
    range: 7,
  },
  {
    id: 'transform_tower',
    name: '变形塔',
    cost: 4,
    tags: ['building', 'blast'],
    kind: 'transform',
    skill: '空地变形',
    description: '按敌我距离切换空地形态并强化。',
    shape: 'building',
    immobile: true,
    range: 5,
  },
  {
    id: 'ukyo',
    name: '橘右京',
    cost: 4,
    tags: ['fighter', 'assassin'],
    kind: 'dash',
    skill: '秘剑细雪',
    description: '突进后连续斩击。',
    shape: 'fighter',
    range: 1,
    assassin: true,
  },
  {
    id: 'nakoruru',
    name: '娜可露露',
    cost: 4,
    tags: ['fighter', 'assassin'],
    kind: 'dash',
    skill: '飞鹰突袭',
    description: '高机动切入敌方后排。',
    shape: 'fighter',
    range: 1,
    assassin: true,
  },
  {
    id: 'athena',
    name: '麻宫雅典娜',
    cost: 5,
    tags: ['fighter', 'ability'],
    kind: 'execute',
    skill: '闪光水晶波',
    description: '造成真实伤害并斩杀低血目标。',
    shape: 'fighter',
    power: 28,
    radius: 2,
  },
  {
    id: 'turtle',
    name: '玄龟',
    cost: 5,
    tags: ['psionic', 'guard'],
    kind: 'shield',
    skill: '玄水结界',
    description: '为全队提供护盾并震慑近敌。',
    shape: 'mystic',
    range: 1,
    radius: 2,
  },
  {
    id: 'bull',
    name: '牛魔王',
    cost: 5,
    tags: ['beast', 'guard'],
    kind: 'stun',
    skill: '撼地怒吼',
    description: '承伤并大范围控制敌人。',
    shape: 'beast',
    range: 1,
    radius: 3,
  },
  {
    id: 'buddha',
    name: '斗战胜佛',
    cost: 5,
    tags: ['vanguard'],
    kind: 'damage',
    skill: '斗战横扫',
    description: '高阶先锋范围横扫。',
    shape: 'fighter',
    range: 1,
    radius: 3,
    power: 300,
  },
];

const colors: Partial<Record<Tag, number>> = {
  infantry: 0x78c8b0,
  cavalry: 0xc99b65,
  armor: 0x9aaab8,
  airforce: 0x75cfee,
  puppet: 0xb99a72,
  psionic: 0xae94d8,
  walker: 0xdfb36f,
  marine: 0x67bad4,
  beast: 0xe5b96f,
  raptor: 0xbe718d,
  insectoid: 0x8ac85f,
  immortal: 0x7f82a6,
  panda: 0xe9ded0,
  building: 0x82a4a8,
  fighter: 0xe86e5c,
};
function effects(row: UnitRow): AbilityEffect[] {
  if (row.id === 'alchemy_tower')
    return [{ trigger: 'victory', target: 'self', kind: 'gold', value: 1 }];
  if (row.id === 'burstbug')
    return [
      {
        trigger: 'death',
        target: 'areaEnemies',
        kind: 'skillDamage',
        value: row.deathBurst ?? 130,
        radius: 1,
      },
    ];
  const target =
    row.id === 'child' || row.id === 'turtle'
      ? 'allAllies'
      : row.kind === 'heal' || row.id === 'repair'
        ? 'lowestHealthAlly'
        : row.kind === 'shield'
          ? 'self'
          : row.id === 'aircrab' || row.id === 'divine_tower'
            ? 'highestAttackEnemy'
            : 'areaEnemies';
  const kind = (
    {
      damage: 'skillDamage',
      heal: 'heal',
      shield: 'shield',
      stun: 'stun',
      poison: 'poison',
      summon: 'summon',
      dash: 'dash',
      buff: 'attack',
      charm: 'taunt',
      execute: 'execute',
      silence: 'disableItems',
      armorBreak: 'armor',
      transform: 'transform',
    } as const
  )[row.kind];
  const actualKind = row.id === 'child' ? 'energy' : kind;
  return [
    {
      trigger: 'cast',
      target,
      kind: actualKind,
      value: row.power ?? 80 + row.cost * 45,
      duration: row.duration ?? 35,
      radius: row.radius ?? 1,
      summonId: row.summonId,
    },
  ];
}
export const UNITS: UnitDefinition[] = rows.map((row, index) => {
  const ranged =
    row.range ??
    (row.tags.includes('guard') || row.tags.includes('vanguard') || row.tags.includes('assassin')
      ? 1
      : row.tags.includes('sniper') || row.tags.includes('siege')
        ? 5
        : 3);
  const attackTiming = {
    windupTicks: 4,
    travelTicks: ranged > 1 ? 3 + (index % 3) : 0,
    recoveryTicks: 4,
  };
  const skillTiming = {
    windupTicks: 5 + row.cost,
    travelTicks: ranged > 1 ? 2 + (index % 5) : 0,
    recoveryTicks: 4 + (index % 4),
  };
  return {
    id: row.id,
    name: row.name,
    cost: row.cost,
    poolCount: RULES.poolByCost[row.cost - 1],
    tags: row.tags,
    hp:
      260 + row.cost * 95 + (row.tags.includes('guard') || row.tags.includes('vanguard') ? 160 : 0),
    attack: 30 + row.cost * 14,
    armor: row.tags.includes('guard') ? 8 : row.tags.includes('blast') ? 3 : 4,
    range: ranged,
    attackTicks: row.tags.includes('sniper') ? 17 : 23,
    attackTiming,
    moveTicks: 7,
    layer: row.layer ?? 'ground',
    targets: ['ground', 'air'],
    skill: {
      name: row.skill,
      description: row.description,
      kind: row.kind,
      power: row.power ?? 80 + row.cost * 45,
      radius: row.radius ?? 1,
      duration: row.duration ?? (row.kind === 'poison' ? 80 : 35),
      cooldown: 100,
      timing: skillTiming,
      effects: effects(row),
    },
    assassin: row.assassin,
    deathBurst: row.deathBurst,
    immobile: row.immobile,
    noAttack: row.noAttack,
    summonId: row.summonId,
    shape: row.shape,
    color: colors[row.tags[0]] ?? 0x9cb0b5,
    combatVisual: {
      attack: `${row.id}-attack`,
      skill: `${row.id}-${row.kind}`,
      primary: colors[row.tags[0]] ?? 0x9cb0b5,
      secondary: 0xffd784 - (index % 8) * 0x080604,
    },
  };
});
export const UNIT_BY_ID = Object.fromEntries(UNITS.map((unit) => [unit.id, unit])) as Record<
  string,
  UnitDefinition
>;
export const UNIT_IDS = rows.map((row) => row.id);
export const COMBAT_VISUALS = Object.fromEntries(
  UNITS.map((unit) => [
    unit.id,
    {
      attackTiming: unit.attackTiming,
      skillTiming: unit.skill.timing,
      combatVisual: unit.combatVisual,
    },
  ]),
);
